const {Router} = require('express')
const router = Router()
const NewsController = require('../controllers/views.controller')
const authMiddlewere = require("../middlewere/auth.middlewere");
const SkillController = require("../controllers/skill.controller");

router.get('/news',NewsController.getNews)
router.post('/createpost',NewsController.createPost)
router.post('/plusaup',NewsController.plusAUP)
router.post('/updatemanaup',NewsController.updateManAUP)
router.get('/getaup',NewsController.getAUP)
router.post('/delman',NewsController.delMan)
router.post('/plusvideo',NewsController.plusVideo)
router.post('/pluscomvak',NewsController.plusComVak)
router.get('/getcomvak',NewsController.getComVak)
router.post('/delcomvak',NewsController.delComVak)
router.post('/createvak',NewsController.createVak)
router.get('/getvakansii',NewsController.getVakansii)
router.post('/editvak',NewsController.editVak)
router.post('/deltisvak',NewsController.delTisVak)
router.post('/getabout',NewsController.getAbout)
router.post('/saveabout',NewsController.saveAbout)
router.post('/pluscompany',NewsController.plusCompany)
router.get('/getgroupcompanyes',NewsController.getGroupCompanyes)
router.post('/delcomgroup',NewsController.delComGroup)
router.post('/editcomgroup',NewsController.editСomGroup)
router.post('/updateposcomgroup',NewsController.updatePosComGroup)
router.post('/getplaces',NewsController.getPlaces)
router.post('/plusplaces',NewsController.plusPlaces)
router.post('/delplace',NewsController.delPlace)
router.post('/createPack',NewsController.createpack)
router.post('/getallpacks',NewsController.getAllPacks)
router.post('/editpriorypack',NewsController.editPrioryPack)
router.post('/updatepack',NewsController.updatePack)
router.post('/createimggallery',NewsController.createImgGallery)
router.post('/getgalleryimgs',NewsController.getGalleryImgs)
router.post('/getcities',NewsController.getCities)
router.post('/createcity',NewsController.createCity)
router.post('/uploadstaticcontact',NewsController.uploadStaticContact)
router.post('/pluscontactparam',NewsController.plusContactParam)
router.post('/createzone',NewsController.createZone)
router.post('/getzones',NewsController.getZones)
router.post('/updatezone',NewsController.updateZone)
router.post('/pluszoneslider',NewsController.plusZoneSlider)
router.post('/getzonesslides',NewsController.getZonesSlides)
router.post('/editprioryzoneslider',NewsController.editPrioryZoneSlider)
router.post('/delzoneslider',NewsController.delZoneSlider)
router.post('/getprogramsslides',NewsController.getProgramsSlides)
router.post('/plusprogramslider',NewsController.plusProgramSlider)
router.post('/delprogramslider',NewsController.delProgramSlider)
router.post('/getprogramspage',NewsController.getProgramsPage)
router.post('/plusprogrampage',NewsController.plusProgramPage)
router.post('/delprogrampage',NewsController.delProgramPage)
router.post('/plustrenersgroup',NewsController.plusTrenersGroup)
router.post('/gettrenersgroup',NewsController.getTrenersGroup)
router.post('/deltrenersgroup',NewsController.delTrenersGroup)
router.post('/plustrenerman',NewsController.plusTrenerMan)
router.post('/gettrenersman',NewsController.getTrenersMan)
router.post('/deltrenerman',NewsController.delTrenerMan)
router.post('/delpacks',NewsController.delPacks)
router.post('/getmobileurls',NewsController.getMobileURLs)
router.post('/updateurlmobileapp',NewsController.updateURLMobileAPP)
router.post('/getallpticesavia',NewsController.getAllPticesAvia)
router.post('/getprogramsavia',NewsController.getProgramsAvia)
router.post('/createpriceavia',NewsController.createPriceAvia)
router.post('/delprice',NewsController.delPrice)
router.post('/delnewspost',NewsController.delNewsPost)
router.post('/updatepost',NewsController.updatePost)
router.post('/reverseprioryaup',NewsController.reversePrioryAUP)
router.post('/emailmess', NewsController.sendContactMessage);


module.exports = router